### ISSUE TITLE
undefined local variable or method `password' for #<Puppet::Parser::TemplateWrapper:0x24910d2d>

### ISSUE THREAD

**Issue by rujim** [jadestorm/puppet-patroni#7]
Hello jadestorm,
Please help me to create right Hiera values for bootstrap_users array.

My code (hieradata/product/lsm/tier/inf/env/2.yaml):

```
profiles::shared::postgresql::patroni::bootstrap_users:
  - 'bamboouser':
    password:
      "password"
    options:
      - 'createrole'
      - 'createdb'
```

Error is:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Failed to parse template patroni/postgresql.yml.erb:
  Filepath: /etc/puppetlabs/code/environments/feature_lsm_6460_bamboo/modules/patroni/templates/postgresql.yml.erb
  Line: 46
  Detail: undefined local variable or method `password' for #<Puppet::Parser::TemplateWrapper:0x24910d2d>
 (file: /etc/puppetlabs/code/environments/feature_lsm_6460_bamboo/modules/patroni/manifests/config.pp, line: 8, column: 16) on node us01vlhapglsm3.saas-n.com
```

Thank you in advance and happy holidays!

**Comment by jadestorm** [comment]
HI @rujim !  Ijust just coming back from the holidays -- to me it looks like you have an extra quote on the createdb line -- could that be what is causing the problem?  Also please try to post both configs encased in an "insert code" block so that it doesn't get parsed into something else by github.

**Comment by rujim** [comment]
Updated.

**Comment by jadestorm** [comment]
Ok so another thing I see here is -- this should be on the same line:
```
    password:
      "password"
```
(change to)
```
    password: "password"
```

If it's not, what's happening is instead of password being treated as a string -- it's being treated as a hashed array -- at which point the module doesn't know what to do with it.  Everything else at least -looks- fine to me.  =)

**Comment by rujim** [comment]
Same error.

**Comment by jadestorm** [comment]
Interesting.  Looks like you found a bug -- try the latest master and also remove the - from before the bamboouser -- ie:

```
profiles::shared::postgresql::patroni::bootstrap_users:
  'bamboouser':
    password: "password"
    options:
      - 'createrole'
      - 'createdb'
```

**Comment by rujim** [comment]
Hello jadestorm,
I reconfigured my Puppet for a current Master branch:

Puppetfile
```
mod 'jadestorm/patroni',
  :git    => 'https://github.com/jadestorm/puppet-patroni.git',
  :branch => 'master'
```

.fixtures.yml
```
    patroni:
      repo: https://github.com/jadestorm/puppet-patroni.git
      ref: master
```

My Hiera code:
hieradata/product/lsm/tier/inf/env/2.yaml
```
profiles::shared::postgresql::patroni::bootstrap_users:
  'bamboouser':
    password: "%{lookup('profiles::lsm::postgresql::bamboouser_db_password')}"
    options:
      - 'createrole'
      - 'createdb'
```

site/profiles/manifests/shared/postgresql/patroni.pp
```
class profiles::shared::postgresql::patroni (
...
Hash $bootstrap_users = {},
){
...
class { '::patroni':
...
bootstrap_users           => $bootstrap_users,
...

```
But I got the same issue:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Failed to parse template patroni/postgresql.yml.erb:
  Filepath: /etc/puppetlabs/code/environments/feature_lsm_6460_bamboo/modules/patroni/templates/postgresql.yml.erb
  Line: 46
  Detail: undefined local variable or method `password' for #<Puppet::Parser::TemplateWrapper:0x61ad3e63>
 (file: /etc/puppetlabs/code/environments/feature_lsm_6460_bamboo/modules/patroni/manifests/config.pp, line: 8, column: 16) on node us01vlhapglsm3.saas-n.com
```
Please, help me to fix its.
Tx!

**Comment by jadestorm** [comment]
Hrm I think I see the problem.  (Btw I don't use Patroni anymore so I'm relying on you to test this)  Basically, I was using password in a variable context, not a "string passed as the hash key".  Please try the latest master commit.  =)

**Comment by rujim** [comment]
Unfortunately, I can't see any changes with my Puppet. Same issue with password.

**Comment by jadestorm** [comment]
If you are getting the exact same error, that would most likely imply that the module didn't update.  (or wouldn't make sense for you to see that exact same error with the current code)  Open up the file it's referencing and go to line 46 and make sure all of the instances of password you see are in quotes.  That should tell us if it updated at all.

**Comment by rujim** [comment]
yes, fixed now! Tx!

**Comment by jadestorm** [comment]
Awesome!  Glad to hear it!  =)  And thanks for pointing out the bug!  I'll get a formal release out hopefully today.

**Comment by rujim** [comment]
Hi Daniel,
I have got a password for my user bamboouser, but w/o options now:
(/etc/patroni/ha-pg-bamboo.yml)
```
pg_hba:
    - local all all md5
    - host all all 0.0.0.0/0 md5
    - host replication replicauser 0.0.0.0/0 md5
    - host replication replicauser all md5
    - host all postgres 0.0.0.0/0 md5
    - host bamboodb bamboouser 0.0.0.0/0 md5
    - hostssl replication replicauser 0.0.0.0/0 md5
  users:
    bamboouser:
      password: pass
  post_bootstrap: echo 'CREATE DATABASE bamboodb OWNER bamboouser;' | psql -q $1
```
2.yaml
```
profiles::shared::postgresql::patroni::bootstrap_users:
  'bamboouser':
    password: "%{lookup('profiles::lsm::postgresql::bamboouser_db_password')}"
    options:
      - 'createrole'
      - 'createdb'
```
Please, verify code for template.

**Comment by jadestorm** [comment]
Hrm.  I suspect the erb processor is setting $settings['options'] and treating that as like a true or false rather than a "does this exist".  Might have to do some shuffling.

**Comment by jadestorm** [comment]
Can you try this latest master tweak?  My logic was all off on that after I took a second look at it -- plus there's a better way to test if a key exists.

**Comment by rujim** [comment]
Last commit doesn't help me to pass options into Patroni conf file (/etc/patroni/ha-pg-bamboo.yml):
```
 - hostssl replication replicauser 0.0.0.0/0 md5
  users:
    bamboouser:
      password: pass
  post_bootstrap: echo 'CREATE DATABASE bamboodb OWNER bamboouser;' | psql -q $1
```
Config (hieradata/product/lsm/tier/inf/env/2.yaml):
```
profiles::shared::postgresql::patroni::bootstrap_users:
  'bamboouser':
    password: "%{lookup('profiles::lsm::postgresql::bamboouser_db_password')}"
    options:
      - 'createrole'
      - 'createdb'
```

BR, 
Ruslan
